# Use docker compose v2 for non swarm deployments
# https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2.4'

services:

  web:
    # Build configuration in dev/Dockerfile
    build: dev
    ports:
      - '8080:8080'
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
