# Use docker compose v2 for non swarm deployments
# https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2.4'

services:

  web:
    # Build configuration in Dockerfile
    build: .
    ports:
      - '8080:8080'
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      # Mount the current directory from the host to /app in the container
      - '.:/app'
      # Mount the /app/node_modules directory from the host
      - '/app/node_modules'
